backend:
  name: git-gateway
  branch: main

media_folder: "public/Pictures"
public_folder: "/Pictures"

media_library:
  name: uploadcare

collections:
  - name: articles
    label: Articles
    folder: "src/content/articles"
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - { name: title, label: Titre, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: text, label: Texte, widget: text }
      - { name: images, label: Images, widget: list, required: false, field: { name: image, widget: image } }
      - { name: video, label: Vidéo, widget: string, required: false }