backend:
  name: git-gateway
  branch: dev

media_folder: public/Pictures
public_folder: /Pictures

collections:
  - name: articles
    label: Articles

    folder: src/content/articles

    create: true
    delete: true

    extension: json
    format: json

    slug: "{{slug}}"

    fields:
      - label: Titre
        name: title
        widget: string

      - label: Date
        name: date
        widget: datetime

      - label: Texte
        name: text
        widget: text

      - label: Images
        name: images
        widget: list
        required: false
        field:
          label: Image
          name: image
          widget: image

      - label: Vidéo
        name: video
        widget: string
        required: false